[18/May/2015 14:53:42] WARNING [django.request:170] Not Found: /
[18/May/2015 14:53:42] WARNING [django.request:170] Not Found: /favicon.ico
[18/May/2015 14:53:43] WARNING [django.request:170] Not Found: /favicon.ico
[18/May/2015 14:56:57] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 64, in get
    raise Exception('test')
Exception: test
[18/May/2015 14:56:59] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 64, in get
    raise Exception('test')
Exception: test
[18/May/2015 14:57:09] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 64, in get
    raise Exception('test')
Exception: test
[18/May/2015 14:57:19] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 64, in get
    raise Exception('test')
Exception: test
[18/May/2015 14:57:29] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 64, in get
    raise Exception('test')
Exception: test
[18/May/2015 14:57:39] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 64, in get
    raise Exception('test')
Exception: test
[18/May/2015 14:57:49] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 64, in get
    raise Exception('test')
Exception: test
[18/May/2015 14:57:59] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 64, in get
    raise Exception('test')
Exception: test
[18/May/2015 15:05:59] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 2, in <module>
    import views
  File "/home/user/projects/django/github/forum/views/__init__.py", line 4, in <module>
    from thread_views import ThreadView, CheckNewPostsView
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 75
    def get(self, request, id):
                              ^
IndentationError: unindent does not match any outer indentation level
[18/May/2015 15:06:09] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 2, in <module>
    import views
  File "/home/user/projects/django/github/forum/views/__init__.py", line 4, in <module>
    from thread_views import ThreadView, CheckNewPostsView
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 75
    def get(self, request, id):
                              ^
IndentationError: unindent does not match any outer indentation level
[18/May/2015 15:06:19] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 2, in <module>
    import views
  File "/home/user/projects/django/github/forum/views/__init__.py", line 4, in <module>
    from thread_views import ThreadView, CheckNewPostsView
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 75
    def get(self, request, id):
                              ^
IndentationError: unindent does not match any outer indentation level
[18/May/2015 15:06:29] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 2, in <module>
    import views
  File "/home/user/projects/django/github/forum/views/__init__.py", line 4, in <module>
    from thread_views import ThreadView, CheckNewPostsView
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 75
    def get(self, request, id):
                              ^
IndentationError: unindent does not match any outer indentation level
[18/May/2015 15:06:39] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 2, in <module>
    import views
  File "/home/user/projects/django/github/forum/views/__init__.py", line 4, in <module>
    from thread_views import ThreadView, CheckNewPostsView
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 75
    def get(self, request, id):
                              ^
IndentationError: unindent does not match any outer indentation level
[18/May/2015 15:06:49] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 2, in <module>
    import views
  File "/home/user/projects/django/github/forum/views/__init__.py", line 4, in <module>
    from thread_views import ThreadView, CheckNewPostsView
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 75
    def get(self, request, id):
                              ^
IndentationError: unindent does not match any outer indentation level
[18/May/2015 15:06:59] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 2, in <module>
    import views
  File "/home/user/projects/django/github/forum/views/__init__.py", line 4, in <module>
    from thread_views import ThreadView, CheckNewPostsView
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 75
    def get(self, request, id):
                              ^
IndentationError: unindent does not match any outer indentation level
[18/May/2015 15:07:09] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 2, in <module>
    import views
  File "/home/user/projects/django/github/forum/views/__init__.py", line 4, in <module>
    from thread_views import ThreadView, CheckNewPostsView
  File "/home/user/projects/django/github/forum/views/thread_views.py", line 75
    def get(self, request, id):
                              ^
IndentationError: unindent does not match any outer indentation level
[18/May/2015 15:11:59] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/check_new_posts/last_loaded=(?P<last_loaded>\d+)/$', views.EditPostView.as_view(),
AttributeError: 'module' object has no attribute 'EditPostView'
[18/May/2015 15:12:09] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/check_new_posts/last_loaded=(?P<last_loaded>\d+)/$', views.EditPostView.as_view(),
AttributeError: 'module' object has no attribute 'EditPostView'
[18/May/2015 15:12:19] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/check_new_posts/last_loaded=(?P<last_loaded>\d+)/$', views.EditPostView.as_view(),
AttributeError: 'module' object has no attribute 'EditPostView'
[18/May/2015 15:12:29] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/check_new_posts/last_loaded=(?P<last_loaded>\d+)/$', views.EditPostView.as_view(),
AttributeError: 'module' object has no attribute 'EditPostView'
[18/May/2015 15:12:49] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/check_new_posts/last_loaded=(?P<last_loaded>\d+)/$', views.EditPostView.as_view(),
AttributeError: 'module' object has no attribute 'EditPostView'
[18/May/2015 15:12:59] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/check_new_posts/last_loaded=(?P<last_loaded>\d+)/$', views.EditPostView.as_view(),
AttributeError: 'module' object has no attribute 'EditPostView'
[18/May/2015 15:13:09] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/check_new_posts/last_loaded=(?P<last_loaded>\d+)/$', views.EditPostView.as_view(),
AttributeError: 'module' object has no attribute 'EditPostView'
[18/May/2015 15:13:19] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/check_new_posts/last_loaded=(?P<last_loaded>\d+)/$', views.EditPostView.as_view(),
AttributeError: 'module' object has no attribute 'EditPostView'
[18/May/2015 15:13:29] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/check_new_posts/last_loaded=(?P<last_loaded>\d+)/$', views.EditPostView.as_view(),
AttributeError: 'module' object has no attribute 'EditPostView'
[18/May/2015 15:13:39] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/check_new_posts/last_loaded=(?P<last_loaded>\d+)/$', views.EditPostView.as_view(),
AttributeError: 'module' object has no attribute 'EditPostView'
[18/May/2015 15:13:49] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:13:59] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:14:09] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:14:19] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:14:29] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:14:39] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:14:49] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:14:59] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:15:09] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:15:19] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:15:29] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:15:39] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:15:49] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:15:59] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:16:09] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:16:19] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:16:29] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:16:39] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:16:49] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:16:52] ERROR [django.request:256] Internal Server Error: /forum/thread/6/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:16:59] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
[18/May/2015 15:17:09] ERROR [django.request:256] Internal Server Error: /forum/thread/6/check_new_posts/last_loaded=1431960928/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum_site/urls.py", line 5, in <module>
    , url(r'^forum/', include('forum.urls', namespace='forum'))
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/django/github/forum/urls.py", line 14, in <module>
    , url(r'^thread/(?P<id>\d+)/post/(?P<post_id>\d+)/edit/$', views.PostEditView.as_view(),
AttributeError: 'module' object has no attribute 'PostEditView'
